/**
 * Server-side x402 configuration utilities for Vercel Functions
 * Generated by x402-agent CLI for rest-express
 *
 * This file is separate from lib/x402/ because Vercel Functions
 * run in a Node.js environment and need their own config loader.
 */

import fs from 'fs';
import path from 'path';

export interface X402Endpoint {
  id: string;
  name: string;
  url: string;
  method: string;
  description: string;
  category?: string;
  parameters: {
    type: 'object';
    properties: Record<string, unknown>;
    required?: string[];
  };
  estimatedCost?: string;
  trusted: boolean;
}

export interface WalletConfig {
  provider: 'cdp-embedded';
  network: 'base' | 'base-sepolia' | 'ethereum' | 'sepolia';
  privateKey: string;
}

export interface X402Config {
  wallet: WalletConfig;
  endpoints: X402Endpoint[];
}

/**
 * Loads x402-endpoints.json configuration
 * Interpolates environment variables in ${VAR} format
 */
export function loadX402Config(): X402Config {
  const configPath = path.resolve(process.cwd(), 'x402-endpoints.json');

  if (!fs.existsSync(configPath)) {
    throw new Error(`x402-endpoints.json not found at: ${configPath}`);
  }

  let configContent = fs.readFileSync(configPath, 'utf-8');

  // Interpolate environment variables
  configContent = configContent.replace(/\$\{(\w+)\}/g, (match, varName) => {
    const value = process.env[varName];
    if (value === undefined) {
      throw new Error(`Environment variable ${varName} is not set`);
    }
    return value;
  });

  const config = JSON.parse(configContent) as X402Config;
  return config;
}

/**
 * Loads just the endpoints array
 */
export function loadX402Endpoints(): X402Endpoint[] {
  const config = loadX402Config();
  return config.endpoints;
}

/**
 * Gets a specific endpoint by ID
 */
export function getEndpoint(endpointId: string): X402Endpoint | undefined {
  const config = loadX402Config();
  return config.endpoints.find(e => e.id === endpointId);
}

/**
 * Validates that an endpoint exists and is trusted
 */
export function validateEndpoint(endpointId: string): {
  valid: boolean;
  error?: string;
  endpoint?: X402Endpoint;
} {
  const endpoint = getEndpoint(endpointId);

  if (!endpoint) {
    return {
      valid: false,
      error: `Endpoint "${endpointId}" not found in configuration`
    };
  }

  if (!endpoint.trusted) {
    return {
      valid: false,
      error: `Endpoint "${endpointId}" is not marked as trusted`,
      endpoint
    };
  }

  return { valid: true, endpoint };
}

/**
 * Convert x402 endpoints to OpenAI function calling format
 * Useful for integrating with LLM APIs (OpenAI, Anthropic, etc.)
 */
export function endpointsToFunctions(endpoints?: X402Endpoint[]) {
  const eps = endpoints || loadX402Endpoints();
  return eps.map(endpoint => ({
    name: endpoint.id,
    description: endpoint.description,
    parameters: endpoint.parameters
  }));
}
