/**
 * x402 configuration loader with environment variable interpolation
 * Generated by x402-agent CLI for rest-express
 */

import { readFileSync } from 'fs';
import { join } from 'path';
import type { X402Config, X402Endpoint } from './types.js';

/**
 * Loads and parses x402-endpoints.json configuration
 * Supports ${ENV_VAR} syntax for environment variable interpolation
 */
export function loadX402Config(configPath?: string): X402Config {
  const defaultPath = join(process.cwd(), 'x402-endpoints.json');
  const path = configPath || process.env.X402_CONFIG_PATH || defaultPath;

  try {
    let configContent = readFileSync(path, 'utf-8');

    // Interpolate environment variables
    configContent = interpolateEnvVars(configContent);

    const config = JSON.parse(configContent) as X402Config;

    // Validate basic structure
    if (!config.wallet || !config.endpoints) {
      throw new Error('Invalid config: missing wallet or endpoints');
    }

    return config;
  } catch (error) {
    throw new Error(
      `Failed to load x402 config from ${path}: ${
        error instanceof Error ? error.message : 'Unknown error'
      }`
    );
  }
}

/**
 * Replaces ${ENV_VAR} placeholders with actual environment variable values
 */
function interpolateEnvVars(content: string): string {
  return content.replace(/\$\{(\w+)\}/g, (match, varName) => {
    const value = process.env[varName];
    if (value === undefined) {
      throw new Error(`Environment variable ${varName} is not set`);
    }
    return value;
  });
}

/**
 * Gets a specific endpoint by ID
 */
export function getEndpoint(
  config: X402Config,
  endpointId: string
): X402Endpoint | undefined {
  return config.endpoints.find(e => e.id === endpointId);
}

/**
 * Gets all trusted endpoints
 */
export function getTrustedEndpoints(config: X402Config): X402Endpoint[] {
  return config.endpoints.filter(e => e.trusted);
}

/**
 * Validates that an endpoint exists and is trusted
 */
export function validateEndpoint(
  config: X402Config,
  endpointId: string
): { valid: boolean; error?: string; endpoint?: X402Endpoint } {
  const endpoint = getEndpoint(config, endpointId);

  if (!endpoint) {
    return {
      valid: false,
      error: `Endpoint "${endpointId}" not found in configuration`
    };
  }

  if (!endpoint.trusted) {
    return {
      valid: false,
      error: `Endpoint "${endpointId}" is not marked as trusted`,
      endpoint
    };
  }

  return { valid: true, endpoint };
}
