/**
 * Payment logging utility for x402 micropayments on Base network
 * Provides structured logging for payment settlements with BaseScan links
 *
 * Generated by x402-agent CLI for rest-express
 */

export interface PaymentSettlement {
  endpoint: string;
  txHash: string;
  estimatedAmount?: number; // in USDC
  timestamp: number;
  baseScanUrl: string;
}

/**
 * Logs a payment settlement with formatted output for console visibility
 * @param endpoint - The endpoint that was called
 * @param txHash - Transaction hash from X-PAYMENT-RESPONSE header
 * @param estimatedAmount - Optional estimated payment amount in USDC
 */
export function logPaymentSettlement(
  endpoint: string,
  txHash: string,
  estimatedAmount?: number
): PaymentSettlement {
  const timestamp = Date.now();
  const baseScanUrl = `https://basescan.org/tx/${txHash}`;

  const settlement: PaymentSettlement = {
    endpoint,
    txHash,
    estimatedAmount,
    timestamp,
    baseScanUrl,
  };

  // Log with visual formatting for easy identification
  console.log('\n' + '='.repeat(80));
  console.log('💰 x402 PAYMENT SETTLED');
  console.log('='.repeat(80));
  console.log(`Endpoint:         ${endpoint}`);
  if (estimatedAmount !== undefined) {
    console.log(`Amount:           ~$${estimatedAmount.toFixed(4)} USDC`);
  }
  console.log(`Transaction:      ${txHash}`);
  console.log(`BaseScan:         ${baseScanUrl}`);
  console.log(`Timestamp:        ${new Date(timestamp).toISOString()}`);
  console.log('='.repeat(80) + '\n');

  return settlement;
}

/**
 * Extracts payment response information from HTTP headers
 * @param response - Fetch Response object
 * @returns Payment info including transaction hash and payment status
 */
export function extractPaymentInfo(response: Response): {
  txHash: string | null;
  paymentMade: boolean;
  paymentRequest?: string;
} {
  const txHash = response.headers.get('X-PAYMENT-RESPONSE');
  const paymentRequest = response.headers.get('X-PAYMENT');

  return {
    txHash,
    paymentMade: txHash !== null,
    paymentRequest: paymentRequest || undefined
  };
}

/**
 * Logs payment initiation (when 402 Payment Required is received)
 * @param endpoint - The endpoint being called
 * @param paymentRequired - The payment amount/details from 402 response
 */
export function logPaymentInitiated(
  endpoint: string,
  paymentRequired: string
): void {
  console.log('\n' + '-'.repeat(80));
  console.log('💳 x402 PAYMENT INITIATED');
  console.log('-'.repeat(80));
  console.log(`Endpoint:         ${endpoint}`);
  console.log(`Payment Required: ${paymentRequired}`);
  console.log('-'.repeat(80) + '\n');
}

/**
 * Logs payment errors
 * @param endpoint - The endpoint that failed
 * @param error - The error that occurred
 */
export function logPaymentError(
  endpoint: string,
  error: Error | string
): void {
  console.error('\n' + '!'.repeat(80));
  console.error('❌ x402 PAYMENT ERROR');
  console.error('!'.repeat(80));
  console.error(`Endpoint:         ${endpoint}`);
  console.error(`Error:            ${error instanceof Error ? error.message : error}`);
  console.error('!'.repeat(80) + '\n');
}
