/**
 * TypeScript types for x402 payment handling
 * Generated by x402-agent CLI for rest-express
 */

export interface X402Endpoint {
  id: string;
  name: string;
  url: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  description: string;
  category?: string;
  parameters: {
    type: 'object';
    properties: Record<string, unknown>;
    required?: string[];
  };
  estimatedCost?: string;
  trusted: boolean;
}

export interface WalletConfig {
  provider: 'cdp-embedded';
  network: 'base' | 'base-sepolia' | 'ethereum' | 'sepolia';
  privateKey: string;
}

export interface X402Config {
  wallet: WalletConfig;
  endpoints: X402Endpoint[];
}

export interface PaymentResult {
  success: boolean;
  data?: unknown;
  txHash?: string;
  paymentMade: boolean;
  error?: string;
}
