/**
 * Wallet setup and x402 payment utilities
 * Generated by x402-agent CLI for rest-express
 */

import { createWalletClient, http, type WalletClient, type Chain } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { base, baseSepolia, mainnet, sepolia } from 'viem/chains';
import { wrapFetchWithPayment } from 'x402-fetch';
import type { WalletConfig } from './types.js';

/**
 * Network chain mapping
 */
const NETWORKS: Record<string, Chain> = {
  'base': base,
  'base-sepolia': baseSepolia,
  'ethereum': mainnet,
  'sepolia': sepolia
};

/**
 * Creates a wallet client configured for x402 payments
 */
export function createX402WalletClient(walletConfig: WalletConfig): WalletClient {
  const chain = NETWORKS[walletConfig.network];
  if (!chain) {
    throw new Error(`Unsupported network: ${walletConfig.network}`);
  }

  // Convert private key to account
  const account = privateKeyToAccount(walletConfig.privateKey as `0x${string}`);

  // Create wallet client
  const walletClient = createWalletClient({
    account,
    chain,
    transport: http()
  });

  return walletClient;
}

/**
 * Creates a fetch function wrapped with x402 payment handling
 * @param walletClient - Viem wallet client for signing payments
 * @param maxPaymentAmount - Maximum payment amount in USDC (with 6 decimals)
 * @returns Wrapped fetch function that handles 402 payments automatically
 */
export function createX402Fetch(
  walletClient: WalletClient,
  maxPaymentAmount: bigint = BigInt(1_000_000) // Default: 1 USDC
) {
  return wrapFetchWithPayment(fetch, walletClient as any, maxPaymentAmount) as typeof fetch;
}

/**
 * Setup helper that creates both wallet client and wrapped fetch
 * @param walletConfig - Wallet configuration from x402-endpoints.json
 * @param maxPaymentUSDC - Maximum payment in USDC (default: 1.0)
 * @returns Object with walletClient and x402Fetch function
 */
export function setupX402Wallet(
  walletConfig: WalletConfig,
  maxPaymentUSDC: number = 1.0
) {
  const walletClient = createX402WalletClient(walletConfig);

  // Convert USDC to wei (6 decimals)
  const maxPaymentAmount = BigInt(Math.floor(maxPaymentUSDC * 1_000_000));

  const x402Fetch = createX402Fetch(walletClient, maxPaymentAmount);

  return {
    walletClient,
    x402Fetch,
    maxPaymentUSDC
  };
}
